"""Add missing columns to audit_logs

Revision ID: be35d24d35c7
Revises: 8952d15dfa26
Create Date: 2026-02-13 18:53:04.277782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be35d24d35c7'
down_revision: Union[str, None] = '8952d15dfa26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('connection_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('connection_name', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('action_type', sa.Enum('CONNECTION_CREATE', 'CONNECTION_UPDATE', 'CONNECTION_DELETE', 'CONNECTION_ACTIVATE', 'CONNECTION_DEACTIVATE', 'CONNECTION_TEST', 'QUERY_EXECUTE', 'QUERY_EXPLAIN', 'SCHEMA_LIST', 'SCHEMA_ACCESS', 'TABLE_LIST', 'TABLE_ACCESS', 'TABLE_CREATE', 'TABLE_DROP', 'PERMISSION_GRANT', 'PERMISSION_REVOKE', 'PERMISSION_VIEW', 'DATA_IMPORT', 'DATA_EXPORT', 'DATA_INSERT', 'DATA_UPDATE', 'DATA_DELETE', 'HEALTH_CHECK', 'CAPABILITY_DETECT', 'USER_LOGIN', 'USER_LOGOUT', 'USER_LOGIN_FAILED', name='auditactiontype'), nullable=True))
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_connection_id'), 'audit_logs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'connection_profiles', ['connection_id'], ['id'], ondelete='SET NULL')
    op.alter_column('connection_health_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_connection_health_logs_id'), 'connection_health_logs', ['id'], unique=False)
    op.create_index(op.f('ix_connection_permissions_id'), 'connection_permissions', ['id'], unique=False)
    op.add_column('connection_profiles', sa.Column('credential_last_rotated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('connection_profiles', sa.Column('credential_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('connection_profiles', sa.Column('credential_rotation_days', sa.Integer(), nullable=False, server_default='90'))
    op.add_column('connection_profiles', sa.Column('encryption_key_version', sa.Integer(), nullable=False, server_default='1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connection_profiles', 'encryption_key_version')
    op.drop_column('connection_profiles', 'credential_rotation_days')
    op.drop_column('connection_profiles', 'credential_expires_at')
    op.drop_column('connection_profiles', 'credential_last_rotated')
    op.drop_index(op.f('ix_connection_permissions_id'), table_name='connection_permissions')
    op.drop_index(op.f('ix_connection_health_logs_id'), table_name='connection_health_logs')
    op.alter_column('connection_health_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_connection_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    op.drop_column('audit_logs', 'action_type')
    op.drop_column('audit_logs', 'connection_name')
    op.drop_column('audit_logs', 'connection_id')
    # ### end Alembic commands ###
